/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as NgoRouteImport } from './routes/ngo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppWeatherRouteImport } from './routes/app.weather'
import { Route as AppTwinRouteImport } from './routes/app.twin'
import { Route as AppScanRouteImport } from './routes/app.scan'
import { Route as AppRiskRouteImport } from './routes/app.risk'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPlannerRouteImport } from './routes/app.planner'
import { Route as AppMoreRouteImport } from './routes/app.more'
import { Route as AppMarketRouteImport } from './routes/app.market'
import { Route as AppLearnRouteImport } from './routes/app.learn'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as ApiPublicTranscribeRouteImport } from './routes/api/public/transcribe'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoRoute = NgoRouteImport.update({
  id: '/ngo',
  path: '/ngo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppWeatherRoute = AppWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AppRoute,
} as any)
const AppTwinRoute = AppTwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicTranscribeRoute = ApiPublicTranscribeRouteImport.update({
  id: '/api/public/transcribe',
  path: '/api/public/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/ngo': typeof NgoRoute
  '/officer': typeof OfficerRoute
  '/otp': typeof OtpRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/community': typeof AppCommunityRoute
  '/app/history': typeof AppHistoryRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/learn': typeof AppLearnRoute
  '/app/market': typeof AppMarketRoute
  '/app/more': typeof AppMoreRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/risk': typeof AppRiskRoute
  '/app/scan': typeof AppScanRoute
  '/app/twin': typeof AppTwinRoute
  '/app/weather': typeof AppWeatherRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/ngo': typeof NgoRoute
  '/officer': typeof OfficerRoute
  '/otp': typeof OtpRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/community': typeof AppCommunityRoute
  '/app/history': typeof AppHistoryRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/learn': typeof AppLearnRoute
  '/app/market': typeof AppMarketRoute
  '/app/more': typeof AppMoreRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/risk': typeof AppRiskRoute
  '/app/scan': typeof AppScanRoute
  '/app/twin': typeof AppTwinRoute
  '/app/weather': typeof AppWeatherRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/ngo': typeof NgoRoute
  '/officer': typeof OfficerRoute
  '/otp': typeof OtpRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/community': typeof AppCommunityRoute
  '/app/history': typeof AppHistoryRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/learn': typeof AppLearnRoute
  '/app/market': typeof AppMarketRoute
  '/app/more': typeof AppMoreRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/risk': typeof AppRiskRoute
  '/app/scan': typeof AppScanRoute
  '/app/twin': typeof AppTwinRoute
  '/app/weather': typeof AppWeatherRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/language'
    | '/login'
    | '/ngo'
    | '/officer'
    | '/otp'
    | '/register'
    | '/welcome'
    | '/app/analytics'
    | '/app/assistant'
    | '/app/community'
    | '/app/history'
    | '/app/insights'
    | '/app/knowledge'
    | '/app/learn'
    | '/app/market'
    | '/app/more'
    | '/app/planner'
    | '/app/profile'
    | '/app/risk'
    | '/app/scan'
    | '/app/twin'
    | '/app/weather'
    | '/admin/'
    | '/app/'
    | '/api/public/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/language'
    | '/login'
    | '/ngo'
    | '/officer'
    | '/otp'
    | '/register'
    | '/welcome'
    | '/app/analytics'
    | '/app/assistant'
    | '/app/community'
    | '/app/history'
    | '/app/insights'
    | '/app/knowledge'
    | '/app/learn'
    | '/app/market'
    | '/app/more'
    | '/app/planner'
    | '/app/profile'
    | '/app/risk'
    | '/app/scan'
    | '/app/twin'
    | '/app/weather'
    | '/admin'
    | '/app'
    | '/api/public/transcribe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/language'
    | '/login'
    | '/ngo'
    | '/officer'
    | '/otp'
    | '/register'
    | '/welcome'
    | '/app/analytics'
    | '/app/assistant'
    | '/app/community'
    | '/app/history'
    | '/app/insights'
    | '/app/knowledge'
    | '/app/learn'
    | '/app/market'
    | '/app/more'
    | '/app/planner'
    | '/app/profile'
    | '/app/risk'
    | '/app/scan'
    | '/app/twin'
    | '/app/weather'
    | '/admin/'
    | '/app/'
    | '/api/public/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LanguageRoute: typeof LanguageRoute
  LoginRoute: typeof LoginRoute
  NgoRoute: typeof NgoRoute
  OfficerRoute: typeof OfficerRoute
  OtpRoute: typeof OtpRoute
  RegisterRoute: typeof RegisterRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiPublicTranscribeRoute: typeof ApiPublicTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo': {
      id: '/ngo'
      path: '/ngo'
      fullPath: '/ngo'
      preLoaderRoute: typeof NgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/weather': {
      id: '/app/weather'
      path: '/weather'
      fullPath: '/app/weather'
      preLoaderRoute: typeof AppWeatherRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/twin': {
      id: '/app/twin'
      path: '/twin'
      fullPath: '/app/twin'
      preLoaderRoute: typeof AppTwinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk': {
      id: '/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planner': {
      id: '/app/planner'
      path: '/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/more': {
      id: '/app/more'
      path: '/more'
      fullPath: '/app/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learn': {
      id: '/app/learn'
      path: '/learn'
      fullPath: '/app/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/transcribe': {
      id: '/api/public/transcribe'
      path: '/api/public/transcribe'
      fullPath: '/api/public/transcribe'
      preLoaderRoute: typeof ApiPublicTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLearnRoute: typeof AppLearnRoute
  AppMarketRoute: typeof AppMarketRoute
  AppMoreRoute: typeof AppMoreRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRiskRoute: typeof AppRiskRoute
  AppScanRoute: typeof AppScanRoute
  AppTwinRoute: typeof AppTwinRoute
  AppWeatherRoute: typeof AppWeatherRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLearnRoute: AppLearnRoute,
  AppMarketRoute: AppMarketRoute,
  AppMoreRoute: AppMoreRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppProfileRoute: AppProfileRoute,
  AppRiskRoute: AppRiskRoute,
  AppScanRoute: AppScanRoute,
  AppTwinRoute: AppTwinRoute,
  AppWeatherRoute: AppWeatherRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LanguageRoute: LanguageRoute,
  LoginRoute: LoginRoute,
  NgoRoute: NgoRoute,
  OfficerRoute: OfficerRoute,
  OtpRoute: OtpRoute,
  RegisterRoute: RegisterRoute,
  WelcomeRoute: WelcomeRoute,
  ApiPublicTranscribeRoute: ApiPublicTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
